name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executable
      run: pyinstaller --onefile tu_script.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/
