name: Build Windows Executable

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pyinstaller

    - name: Generate .spec file
      run: pyinstaller --onefile --name=Sistema_Lector_de_Facturas_Windows Sistema_Lector_de_Facturas.py

    - name: List files in current directory
      run: dir

    - name: Build executable from .spec file
      run: pyinstaller Sistema_Lector_de_Facturas_Windows.spec

    - name: Upload .spec file
      uses: actions/upload-artifact@v2
      with:
        name: spec-file
        path: Sistema_Lector_de_Facturas_Windows.spec

    - name: Upload dist folder
      uses: actions/upload-artifact@v2
      with:
        name: dist-folder
        path: dist
